#!/bin/bash
# ${PROJECT} — Staging deploy
# Generated by /staging skill.
#
# Usage:
#   ./scripts/deploy-staging.sh              # Pull, build, swap apps
#   ./scripts/deploy-staging.sh --migrate    # + run migrations
#   ./scripts/deploy-staging.sh --seed       # + run seeds
#   ./scripts/deploy-staging.sh --no-pull    # Skip git pull (use local code)
#
# This script does NOT touch prod containers (gateway, postgres, redis).
# It only builds and swaps the staging app/api/website/worker containers.

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

COMPOSE_FILE="docker/docker-compose.staging.yml"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BRANCH="${BRANCH:-main}"

cd "$PROJECT_DIR"

MIGRATE=false; SEED=false; PULL=true
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --migrate) MIGRATE=true ;;
    --seed) SEED=true ;;
    --no-pull) PULL=false ;;
    --help) echo "Usage: $0 [--migrate] [--seed] [--no-pull]"; exit 0 ;;
    *) echo -e "${RED}Unknown: $1${NC}"; exit 1 ;;
  esac
  shift
done

echo -e "${GREEN}=== ${PROJECT} staging deploy ===${NC}"

if [ ! -f ".env.staging" ]; then
  echo -e "${RED}Missing .env.staging — copy from .env.staging.example and fill secrets${NC}"
  exit 1
fi

if [ "$PULL" = true ]; then
  echo -e "${YELLOW}[1/4] git pull origin $BRANCH${NC}"
  git fetch origin
  git checkout $BRANCH
  git pull origin $BRANCH
fi

echo -e "${YELLOW}[2/4] Build staging images${NC}"
docker compose -f $COMPOSE_FILE build

echo -e "${YELLOW}[3/4] Swap staging containers${NC}"
docker compose -f $COMPOSE_FILE up -d

echo -e "${YELLOW}Waiting for staging api...${NC}"
RETRIES=30
until docker compose -f $COMPOSE_FILE exec -T api-staging wget -q --spider http://localhost:8080/health 2>/dev/null || [ $RETRIES -eq 0 ]; do
  sleep 2; RETRIES=$((RETRIES-1))
done
[ $RETRIES -eq 0 ] && echo -e "${RED}WARN: api-staging health check did not pass${NC}"

if [ "$MIGRATE" = true ]; then
  echo -e "${YELLOW}[3a/4] Run migrations${NC}"
  docker compose -f $COMPOSE_FILE exec -T api-staging npm run migration:run || {
    echo -e "${RED}Migration failed${NC}"; exit 1; }
fi

if [ "$SEED" = true ]; then
  echo -e "${YELLOW}[3b/4] Run seeds${NC}"
  docker compose -f $COMPOSE_FILE exec -T api-staging npm run seed:run || {
    echo -e "${RED}Seed failed${NC}"; exit 1; }
fi

echo -e "${YELLOW}[4/4] Reload prod gateway to pick up any nginx changes${NC}"
docker exec ${PROD_GATEWAY_CONTAINER} nginx -s reload || true

echo ""
echo -e "${GREEN}=== Deploy complete ===${NC}"
echo "  App:     https://${STAGING_APP_HOST}"
echo "  API:     https://${STAGING_API_HOST}"
echo "  Website: https://${STAGING_HOST}"
echo ""
docker compose -f $COMPOSE_FILE ps
