# ${PROJECT} — Staging stack (partial)
# Shares prod nginx-gateway, postgres, and redis containers.
# Only the application services are duplicated with -staging suffix.
#
# Generated by /staging skill. Re-run skill to regenerate.

networks:
  default:
    name: ${PROJECT_NETWORK}
    external: true

services:
  api-staging:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: ${PROJECT}-api-staging
    restart: unless-stopped
    env_file:
      - ../.env.staging
    environment:
      - NODE_ENV=staging
      - PORT=8080
      - HOST=0.0.0.0
      - DB_HOST=${PROD_POSTGRES_CONTAINER}
      - DB_PORT=5432
      - DB_NAME=${PROJECT}_staging
      - REDIS_HOST=${PROD_REDIS_CONTAINER}
      - REDIS_PORT=6379
      - REDIS_DB=1
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  app-staging:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
      args:
        NEXT_PUBLIC_API_URL_BASE: https://${STAGING_API_HOST}
        NEXT_PUBLIC_APP_URL: https://${STAGING_APP_HOST}
    container_name: ${PROJECT}-app-staging
    restart: unless-stopped
    env_file:
      - ../.env.staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL_BASE=https://${STAGING_API_HOST}
      - NEXT_PUBLIC_APP_URL=https://${STAGING_APP_HOST}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  website-staging:
    build:
      context: ..
      dockerfile: docker/website.Dockerfile
      args:
        NEXT_PUBLIC_API_URL_BASE: https://${STAGING_API_HOST}
        NEXT_PUBLIC_WEBSITE_URL: https://${STAGING_HOST}
    container_name: ${PROJECT}-website-staging
    restart: unless-stopped
    env_file:
      - ../.env.staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL_BASE=https://${STAGING_API_HOST}
      - NEXT_PUBLIC_APP_URL=https://${STAGING_APP_HOST}
      - NEXT_PUBLIC_WEBSITE_URL=https://${STAGING_HOST}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  worker-staging:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    container_name: ${PROJECT}-worker-staging
    restart: unless-stopped
    env_file:
      - ../.env.staging
    environment:
      - NODE_ENV=staging
      - WORKER_MODE=true
      - WORKER_CONCURRENCY=2
      - DB_HOST=${PROD_POSTGRES_CONTAINER}
      - DB_PORT=5432
      - DB_NAME=${PROJECT}_staging
      - REDIS_HOST=${PROD_REDIS_CONTAINER}
      - REDIS_PORT=6379
      - REDIS_DB=1
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
