# ${PROJECT} — Staging Prerequisites Checklist

Generated by `/staging` skill on $(date +%Y-%m-%d). Complete every item before running `pnpm ship:staging`.

## 1. DNS (manual, by domain registrar)

Add three A records pointing at the prod droplet IP **${DROPLET_IP}**:

| Type | Hostname | Value |
|---|---|---|
| A | `${STAGING_HOST}` | `${DROPLET_IP}` |
| A | `${STAGING_APP_HOST}` | `${DROPLET_IP}` |
| A | `${STAGING_API_HOST}` | `${DROPLET_IP}` |

Verify:
```sh
dig +short ${STAGING_HOST}      # → ${DROPLET_IP}
dig +short ${STAGING_APP_HOST}  # → ${DROPLET_IP}
dig +short ${STAGING_API_HOST}  # → ${DROPLET_IP}
```

## 2. WorkOS dashboard (manual)

1. Open https://dashboard.workos.com
2. **Switch to Staging environment** (top-right env switcher).
3. Go to https://dashboard.workos.com/redirects and add:
   - `https://${STAGING_APP_HOST}/auth/callback`
4. Go to https://dashboard.workos.com/api-keys and generate a staging API key.
5. Copy the staging **Client ID** (visible in dashboard).
6. Paste both into `.env.staging`:
   ```
   WORKOS_API_KEY=sk_staging_...
   WORKOS_CLIENT_ID=client_...
   ```

## 3. SSL certificate (manual, on droplet)

Check whether the existing prod cert already covers the staging hostnames:
```sh
ssh ${SSH_USER}@${DROPLET_IP} "echo | openssl s_client -connect ${PROD_DOMAIN}:443 -showcerts 2>/dev/null | openssl x509 -text -noout | grep -E 'DNS:'"
```

If `${STAGING_HOST}` etc. are missing, expand the cert (after DNS propagates):
```sh
ssh ${SSH_USER}@${DROPLET_IP} <<'EOF'
cd /opt/${PROJECT}  # or wherever the project lives
docker run -it --rm \
  -v $(pwd)/docker/certbot/conf:/etc/letsencrypt \
  -v $(pwd)/docker/certbot/www:/var/www/certbot \
  certbot/certbot certonly --webroot -w /var/www/certbot \
  -d ${PROD_DOMAIN} -d app.${PROD_DOMAIN} -d api.${PROD_DOMAIN} \
  -d ${STAGING_HOST} -d ${STAGING_APP_HOST} -d ${STAGING_API_HOST} \
  --expand --email YOUR_EMAIL@${PROD_DOMAIN} --agree-tos --no-eff-email
EOF
```

Then reload the prod gateway:
```sh
ssh ${SSH_USER}@${DROPLET_IP} "docker exec ${PROD_GATEWAY_CONTAINER} nginx -s reload"
```

## 4. Staging database (one-time, on droplet)

Generate a staging DB password locally:
```sh
openssl rand -base64 32
```
Paste it into `.env.staging` as `DB_PASSWORD=...`.

Then create the staging DB and user. From your laptop:
```sh
# Replace :STAGING_PASSWORD: in the SQL with the value you just generated
sed "s|:STAGING_PASSWORD:|YOUR_GENERATED_PASSWORD|" scripts/init-staging-db.sql \
  | ssh ${SSH_USER}@${DROPLET_IP} "docker exec -i ${PROD_POSTGRES_CONTAINER} psql -U postgres"
```

Verify:
```sh
ssh ${SSH_USER}@${DROPLET_IP} "docker exec ${PROD_POSTGRES_CONTAINER} psql -U postgres -l" | grep ${PROJECT}_staging
```

## 5. Sync `.env.staging` to droplet

```sh
scp .env.staging ${SSH_USER}@${DROPLET_IP}:/opt/${PROJECT}/.env.staging
```

## 6. Droplet capacity check

```sh
ssh ${SSH_USER}@${DROPLET_IP} "free -m && df -h /"
```
Need **≥1 GB available RAM** and **≥3 GB free disk**. If tight, run `docker image prune -a` first.

## 7. First deploy

From your laptop:
```sh
pnpm ship:staging:migrate   # First time — runs migrations
# Subsequent deploys:
pnpm ship:staging
```

## 8. Smoke test

```sh
curl -s https://${STAGING_API_HOST}/health
# → {"status":"ok",...}

open https://${STAGING_APP_HOST}/signup
```

## 9. Hand to QA

Open `_r&d/staging/QA-ONBOARDING.md` and Slack/email the contents to the QA hire.

---

**Done?** Track which items are complete here:

- [ ] DNS records propagated
- [ ] WorkOS staging API key + Client ID in `.env.staging`
- [ ] SSL cert expanded
- [ ] Staging DB created
- [ ] `.env.staging` on droplet
- [ ] First deploy succeeded
- [ ] Smoke test green
- [ ] QA notified
