# ${PROJECT} — Staging SSL configuration
# Loaded by the production nginx-gateway alongside ssl.conf.
# Generated by /staging skill.
#
# Cert must cover: ${STAGING_HOST}, ${STAGING_APP_HOST}, ${STAGING_API_HOST}
# Reissue with --expand if not already covered (see PREREQUISITES.md).

upstream ${PROJECT}_app_staging_backend {
  server ${PROJECT}-app-staging:3000;
}

upstream ${PROJECT}_api_staging_backend {
  server ${PROJECT}-api-staging:8080;
}

upstream ${PROJECT}_website_staging_backend {
  server ${PROJECT}-website-staging:3000;
}

# ====================================================
# STAGING APP — ${STAGING_APP_HOST}
# ====================================================
server {
  listen 443 ssl http2;
  server_name ${STAGING_APP_HOST};

  ssl_certificate     /etc/letsencrypt/live/${PROD_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${PROD_DOMAIN}/privkey.pem;

  limit_req zone=web_limit burst=50 nodelay;
  limit_conn conn_limit_per_ip 20;

  location / {
    proxy_pass http://${PROJECT}_app_staging_backend;
    proxy_http_version 1.1;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 60s;
    proxy_connect_timeout 60s;
  }

  error_page 502 503 504 /maintenance.html;
  location = /maintenance.html {
    root /usr/share/nginx/html;
    internal;
  }
}

# ====================================================
# STAGING API — ${STAGING_API_HOST}
# ====================================================
server {
  listen 443 ssl http2;
  server_name ${STAGING_API_HOST};

  ssl_certificate     /etc/letsencrypt/live/${PROD_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${PROD_DOMAIN}/privkey.pem;

  client_max_body_size 50M;
  limit_req zone=api_limit burst=20 nodelay;
  limit_conn conn_limit_per_ip 10;

  location / {
    proxy_pass http://${PROJECT}_api_staging_backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 120s;
    proxy_connect_timeout 60s;
  }

  error_page 502 503 504 /maintenance.html;
  location = /maintenance.html {
    root /usr/share/nginx/html;
    internal;
  }
}

# ====================================================
# STAGING WEBSITE — ${STAGING_HOST}
# ====================================================
server {
  listen 443 ssl http2;
  server_name ${STAGING_HOST};

  ssl_certificate     /etc/letsencrypt/live/${PROD_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${PROD_DOMAIN}/privkey.pem;

  limit_req zone=web_limit burst=50 nodelay;
  limit_conn conn_limit_per_ip 20;

  location / {
    proxy_pass http://${PROJECT}_website_staging_backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 60s;
    proxy_connect_timeout 60s;
  }

  error_page 502 503 504 /maintenance.html;
  location = /maintenance.html {
    root /usr/share/nginx/html;
    internal;
  }
}

# ====================================================
# HTTP → HTTPS redirect for staging hostnames
# ====================================================
server {
  listen 80;
  server_name ${STAGING_HOST} ${STAGING_APP_HOST} ${STAGING_API_HOST};

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}
